// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";
import * as path from "path";

// Load environment files in order of precedence
// (local dev convenience only; in CI/production DATABASE_URL is injected)
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

// `prisma generate` (including @prisma/client's postinstall hook during
// `npm ci`) loads this config but does NOT need a reachable database.
// Throwing here broke CI and Docker builds where DATABASE_URL isn't set yet.
// Only `migrate` commands require a real URL, and they validate themselves.
const databaseUrl =
  process.env["DATABASE_URL"] ?? "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
